### ISSUE TITLE
Reformat protocols in YAML using terms in FAIR eDNA checklist

### ISSUE THREAD

**Issue by lukenoaa** [aomlomics/protocols#11]

**Comment by lukenoaa** [comment]
YAML is machine readable but more human readable than XML or JSON.

This applies primarily to PCR, where current FAIR eDNA terms are:

- pcr_0_1
- thermocycler
- amplificationReactionVolume
- assay_name
- assay_validation
- targetTaxonomicAssay
- targetTaxonomicScope
- target_gene
- target_subfragment
- ampliconSize
- pcr_primer_forward
- pcr_primer_reverse
- pcr_primer_name_forward
- pcr_primer_name_reverse
- pcr_primer_reference_forward
- pcr_primer_reference_reverse
- pcr_primer_vol_forward
- pcr_primer_vol_reverse
- pcr_primer_conc_forward
- pcr_primer_conc_reverse
- probeReporter
- probeQuencher
- probe_seq
- probe_ref
- probe_conc
- commercial_mm
- custom_mm
- pcr_dna_vol
- pcr_rep
- nucl_acid_amp
- pcr_cond
- annealingTemp
- pcr_cycles
- pcr_analysis_software
- pcr_method_additional

**Comment by lukenoaa** [comment]
@sammyharding This is what we were talking about today. I think you could start with one of the PCR protocols.

**Comment by lukenoaa** [comment]
I see three ways to add tags:

#### 1. YAML Front Matter

Put all of the FAIR eDNA fields at the top (the values will appear twice in the document). Example:

```
---
thermocycler: Eppendorf Mastercycler Nexus Thermal Cycler
amplificationReactionVolume: 25
assay_name: ssu16sv4v5_emp
---
# My Protocol
This is where your Markdown content goes.
```

#### 2. YAML in Code Blocks

Insert FAIR eDNA tags as YAML throughout document (could be used in combination with front matter) using a code block. Fewer values will be duplicated, but probably will have to duplicate some:

```yaml
pcr_primer_forward: GTGYCAGCMGCCGCGGTAA
pcr_primer_reverse: CCGYCAATTYMTTTRAGTTT
pcr_primer_name_forward: 515F-Y
pcr_primer_name_reverse: 926R
```

#### 3. In-line XML tags

Insert XML tags in-line so the rendered version looks the same and there's no duplication of values. In some cases, we would have longer XML tables, which are very machine readable and arguably easier to format than Markdown tables, but do not render nicely for the user. Examples:

```
We used thermocycler model <thermocycler>Eppendorf Mastercycler Nexus Thermal Cycler</thermocycler>.
```

```xml
<pcrPrimers>
    <primer>
        <pcr_primer_name_forward>515F-Y</pcr_primer_name_forward>
        <direction>forward</direction>
        < pcr_primer_forward >GTGYCAGCMGCCGCGGTAA</pcr_primer_forward >
        <sequenceWithAdapters>ACACTGACGACATGGTTCTACA xxx GTGYCAGCMGCCGCGGTAA</sequenceWithAdapters>
        <fluidigmAdapter>CS1-TS-F</fluidigmAdapter>
    </primer>
    <primer>
        <pcr_primer_name_reverse>926R</pcr_primer_name_reverse>
        <direction>reverse</direction>
        <pcr_primer_reverse>CCGYCAATTYMTTTRAGTTT</pcr_primer_reverse>
        <sequenceWithAdapters>TACGGTAGCAGAGACTTGGTCT xxx CCGYCAATTYMTTTRAGTTT</sequenceWithAdapters>
        <fluidigmAdapter>CS2-TS-R</fluidigmAdapter>
    </primer>
</pcrPrimers>
```

**Comment by lukenoaa** [comment]
My current preference is **1 - YAML Frontmatter WITH Jekyll (or Hugo)**. This would allow us to have all the terms at the top in the YAML frontmatter, then reference those terms when they appear in the Markdown body. Example (I put this file in the repo but it doesn't render correctly yet):

```
---
title: "My Document"
author: "John Doe"
date: "2024-11-16"
---

# {{ page.title }}

Written by {{ page.author }} on {{ page.date }}.
```

The downside is most Markdown renderers don't support Jekyll natively. So far it looks like the best way to get the documents to render the content for viewing and printing is GitHub Pages. We could make a GitHub Pages site for our AOML protocols repository.

**Comment by lukenoaa** [comment]
@sammyharding Could you pull out the FAIR eDNA terms/values for:

- protocol_sampling_sterivex_ctd.md
- protocol_libprep_metag_illumina.md
- protocol_pcr_ssu12sv5v6_mifish.md (terms added already)

The latest versions of these protocols are in the GitHub repository. Thank you!

**Comment by sammyharding** [comment]
I added the FAIR eDNA terms/values for the 3 protocols you listed above. I committed the changes to the main branch. For the sampling and library prep protocols, I left some data fields blank because they are specific to each sample and/or I don't have the information. Let me know if I need to make changes. Thanks!

**Comment by lukenoaa** [comment]
Can you change the last MIOP term in all protocols to:
```
publisher: NOAA's Atlantic Oceanographic and Meteorological Laboratory
```

**Comment by sammyharding** [comment]
Done!

**Comment by lukenoaa** [comment]
Awesome, thanks. Congrats on your first commits!
